# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35faf33b0b91fb00775c053a1b4d1863"
name = "packwire"
handle = "packwire"
application_url = "https://commentary-s-logic-o.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "manav-prime.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://commentary-s-logic-o.trycloudflare.com/auth/callback",
  "https://commentary-s-logic-o.trycloudflare.com/auth/shopify/callback",
  "https://commentary-s-logic-o.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
